---
- name: Deploy application
  hosts: app
  tags: deploy-tag
  vars:
    home_dir: /home/sologm
    app_dir: "{{ home_dir }}/reddit"
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        version: monolith
        dest: "{{ app_dir }}"
      notify: reload puma
    - name: Bundle install
      bundler:
        state: present
        chdir: "{{ app_dir }}"
  handlers:
  - name: reload puma
    become: true
    systemd:
      name: puma
      state: restarted
