---
- name: Configure hosts & deploy application
  hosts: all
  vars:
    home_dir: /home/sologm
    app_dir: "{{ home_dir }}/reddit"
    mongo_bind_ip: "127.0.0.1,{{ hostvars['dbserver'].internal_ip }}"
    db_host: "{{ hostvars['dbserver'].internal_ip }}"
  tasks:
    - name: Change MongoDb config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod
    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: "{{ home_dir }}/db_config"
      tags: app-tag
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        version: monolith
        dest: "{{ app_dir }}"
      tags: deploy-tag
      notify: reload puma
    - name: Bundle install
      bundler:
        state: present
        chdir: "{{ app_dir }}"
      tags: deploy-tag
    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag
  handlers:
  - name: restart mongod
    become: true
    service:
      name: mongod
      state: restarted
  - name: reload puma
    become: true
    systemd:
      name: puma
      state: restarted
