---
- name: Configure MongoDb
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: "127.0.0.1,{{ hostvars['dbserver'].internal_ip }}"
  tasks:
    - name: Change MongoDb config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod
  handlers:
  - name: restart mongod
    service:
      name: mongod
      state: restarted
- name: Configure App
  hosts: app
  tags: app-tag
  become: true
  vars:
    home_dir: /home/sologm
    db_host: "{{ hostvars['dbserver'].internal_ip }}"
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: "{{ home_dir }}/db_config"
        owner: sologm
        group: sologm
    - name: enable puma
      systemd: name=puma enabled=yes
  handlers:
  - name: reload puma
    become: true
    systemd:
      name: puma
      state: restarted
- name: Deploy application
  hosts: app
  tags: deploy-tag
  vars:
    home_dir: /home/sologm
    app_dir: "{{ home_dir }}/reddit"
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        version: monolith
        dest: "{{ app_dir }}"
      notify: reload puma
    - name: Bundle install
      bundler:
        state: present
        chdir: "{{ app_dir }}"
  handlers:
  - name: reload puma
    become: true
    systemd:
      name: puma
      state: restarted
